- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  vars_files:
    - ../vars/main.yml

  tasks:

  - name: Install httpie and haproxy
    yum:
      name: [httpie,haproxy]
      state: latest
    notify:
      - start_HAproxy  

  - name: configure haproxy
    template:
      src: ../templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
      - restart_HAproxy  

  handlers:
  - import_tasks: ../handlers/main.yml
