# handlers for HAproxy
- name: start_HAproxy
  service:
    name: haproxy
    state: started

- name: restart_HAproxy
  service:
    name: haproxy
    state: restarted

# handlers for tomcat
- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes

- name: start tomcat
  service:
    name: tomcat
    state: started
